This is makeindex, version 2.15 [MiKTeX 2.9 64-bit] (kpathsea + Thai support).
Scanning style file E:/Cloud/Dropbox/UCSC/4th year/SCS4001 Research/Thesis/Latex/Thesis-Main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Thesis-Main.acn....done (19 entries accepted, 0 rejected).
Sorting entries....done (79 comparisons).
Generating output file Thesis-Main.acr....done (53 lines written, 0 warnings).
Output written in Thesis-Main.acr.
Transcript written in Thesis-Main.alg.
